- src/main/resources/lib/hudson/matrix-project/matrix.jelly
Display axis name in matrix table.
If exists same values in different axises, matrix table is difficult to read.
I think this is hard to understand the results of the test
> Display axis name

- src/main/java/hudson/matrix/AxisDescriptor.java
- src/main/java/hudson/matrix/JDKAxis.java
- src/main/java/hudson/matrix/LabelExpAxis.java
- src/main/java/hudson/matrix/MatrixProject.java
- src/main/java/hudson/matrix/TextAxis.java
- src/main/resources/hudson/matrix/Messages.properties
- src/test/java/hudson/matrix/AxisDescriptorTest.java
- src/test/java/hudson/matrix/AxisTest.java
Fixes [JENKINS-9277](https://issues.jenkins-ci.org/browse/JENKINS-9277), [JENKINS-25448](https://issues.jenkins-ci.org/browse/JENKINS-25448), [JENKINS-23614](https://issues.jenkins-ci.org/browse/JENKINS-23614).
From now on:
- Axis needs to provide non-empty name otherwise form submission is rejected.
- Axis name can not contain `=`and `,`, values can not contain `,` as those have special meaning. Form submission is rejected in such a case.
- Empty list of axis values are allowed, though I am not aware of any use case for that.
> [FIXED JENKINS-9277 JENKINS-25448 JENKINS-23614] Disallow special chars in axis names and values

- pom.xml
- src/main/java/hudson/matrix/MatrixConfiguration.java
[JENKINS-26582](https://issues.jenkins-ci.org/browse/JENKINS-26582)
@reviewbybees
> [JENKINS-26582] Ignore attempts to schedule a MatrixConfiguration directly

- pom.xml
This seems necessary for tests to pass.
> Add more PermGen

- src/test/java/hudson/matrix/MatrixProjectTest.java
- src/test/resources/hudson/matrix/echo-property.pom
The `@RandomlyFails` has been there for ages, but it's failing consistently in my machine. It seems to be an issue with `maven-antrun-extended-plugin:1.40` pom, upgrading to 1.42 in the test pom makes the test pass always (at least in my last 10 runs).
@reviewbybees
> Fix test that failed randomly (?)

- src/main/java/hudson/matrix/MatrixProject.java
https://issues.jenkins-ci.org/browse/JENKINS-33230
> [JENKINS-33230] Disable WARNING log when folder is already existed

- src/main/java/hudson/matrix/DefaultMatrixExecutionStrategyImpl.java
- src/test/resources/hudson/matrix/echo-property.pom
Before this change a build failure returning an NPE could happen when calling getCauseOfBlockage() for matrix projects sitting in the jenkins queue for more than 5 seconds. Specifically it could happen that jenkins asynchronously scheduled the build run between the original `null` checks and the call to getCauseOfBlockage().
> Fix race condition

- src/main/java/hudson/matrix/MatrixBuild.java
- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/test/java/hudson/matrix/RestartingRestoreTest.java
Allows to retrieve the parent build in case Jenkins has restarted.
> Persist the parent in ParentBuildAction

- src/main/java/hudson/matrix/FilterScript.java
This fixes a crash caused by passing a Credentials parameter to a Matrix build.
> Argument passed to createVariableResolver() must never be null.

- src/test/java/hudson/matrix/CombinationFilterUsingBuildParamsTest.java
[JENKINS-44467](https://issues.jenkins-ci.org/browse/JENKINS-44467)
Fixes the mocking of `MatrixBuildListener#all` 
@reviewbybees
> [JENKINS-44467] Matrix project CombinationFilterUsingBuildParamsTest is failling on the PCT

- src/main/java/hudson/matrix/MatrixAggregatable.java
- src/main/java/hudson/matrix/MatrixBuild.java
This allows you to stop using `implements MatrixAggregatable` on publishers, which forces a hard dep on this plugin, and start using an optional extension.
@reviewbybees
> Allow MatrixAggregatable to be registered as an (optional) extension

- src/main/java/hudson/matrix/MatrixBuild.java
- src/main/java/hudson/matrix/MatrixRun.java
- src/main/resources/hudson/matrix/Messages.properties
- src/main/resources/hudson/matrix/Messages_da.properties
- src/main/resources/hudson/matrix/Messages_de.properties
- src/main/resources/hudson/matrix/Messages_es.properties
- src/main/resources/hudson/matrix/Messages_ja.properties
- src/main/resources/hudson/matrix/Messages_nl.properties
- src/main/resources/hudson/matrix/Messages_pt.properties
- src/main/resources/hudson/matrix/Messages_pt_BR.properties
- src/main/resources/hudson/matrix/Messages_tr.properties
- src/main/resources/hudson/matrix/Messages_zh_CN.properties
- src/main/resources/hudson/matrix/Messages_zh_TW.properties
- src/main/resources/hudson/model/Run/confirmDelete.jelly
- src/test/java/hudson/matrix/MatrixProjectTest.java
These changes allow users to delete matrix builds even if they previously were supposed to be kept. 
See JENKINS-26281 and JENKINS-13554 for more details.
> [JENKINS-26281] Matrix builds can be deleted

- src/test/java/hudson/matrix/MatrixProjectTest.java
See [JENKINS-49201](https://issues.jenkins-ci.org/browse/JENKINS-49201)
`MatrixProjectTest#deletedLockedChildrenBuild` and `MatrixProjectTest#deletedLockedParentBuild` try to submit the "doDelete" action form. However, when these tests are executed forcing a newer jenkins-core version (via PCT for example), they fail since there are more than 2 forms and the "doDelete" action form is still the last one.
@olivergondza @reviewbybees
> [JENKINS-49201] Preventing errors when the "doDelete" form is submitted in test execution

- src/test/java/hudson/matrix/CombinationFilterUsingBuildParamsTest.java
PCT fails with:
```
...
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at …
```
> Fix build on Java11 because of PowerMock

- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- pom.xml
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944 in PCT. https://github.com/jenkinsci/jenkins/pull/4944/commits/b45ffbceb4f5cfa1dd91e1ff7ba7f57e8639b4da only covers the common case that an inner `TestBuilder` is saved to one list; however in https://github.com/jenkinsci/matrix-project-plugin/blob/32aea35d4f06c810f7c11d3dc0d599f4af91a097/src/test/java/hudson/matrix/MatrixProjectTest.java#L683-L689 the first save works with only a warning but the second fails, and there is no known way to detect that the error in the second save should be ignored.
> Update parent POM

- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/test/java/hudson/matrix/MatrixConfigurationTest.java
For context see jenkinsci/jenkins#5139
This has also been manually verified to not show the warning.
A test has been added to ensure the next number is always greater than the number of builds.
> [JENKINS-37292] Update default nextBuildBumber to avoid warning on load

- src/test/java/hudson/matrix/AxisTest.java
This is to add forward compatibility due to changes in this PR https://github.com/jenkinsci/jenkins/pull/8418
Without this fix, when you run the PCT the AxisTests fail with:
`org.htmlunit.ElementNotFoundException: elementName=[a] attributeName=[<text>] attributeValue=[User-defined Axis]`
See similar commit for another plugin https://github.com/jenkinsci/script-security-plugin/commit/23895f409fbdbd3419565e2530a6c29a283ca399
Ran mvn verify and ran the PCT test. All green 😄 
```[tasklist]
```
> Forward compatibility with core version 2.422+

- src/main/resources/hudson/tasks/test/MatrixTestResult/index.jelly
`4em` is too narrow for texts like `6 hr 17 min` to fit into: It is shown on two lines as:
> 6 hr 17
> min
The German translation is even worse, which spans 4 lines:
> 6
> Stunden
> 17
> Minuten
which make the table take up too much space.
```console
```
```[tasklist]
```
> style(MatrixTestResult): Increase column width for duration

- src/test/java/hudson/matrix/AxisTest.java
https://github.com/jenkinsci/bom/issues/615 describes the problem in more detail.
When the git plugin is loaded along with the matrix project plugin, there are multiple input fields on the job configuration page with the name `_.name`.  The previous code waited until there was at least one input field with the name `_.name`, but instead it needs to wait for the arrival of an additional input field with the name `_.name`.
Adds a new `setName` method that sets the value of the `_.name` field that was created by this plugin.  Previously, it would set the first `_.name` field.  Setting the first `_.name` field works when running the matrix plugin tests without the git plugin loaded, but fails when the git plugin is loaded.
The combination of waiting for the correct `_.name` field to appear …
> Fix `AxisTest#submitInvalidAxisValue` for plugin BOM

- src/main/java/hudson/matrix/Axis.java
- src/main/java/hudson/matrix/Combination.java
- src/main/java/hudson/matrix/LinkedLogRotator.java
- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/main/java/hudson/matrix/MatrixExecutionStrategy.java
The methods are already listed as deprecated in their Javadoc.  Let's silence the compiler warnings by annotating them as deprecated.
Confirmed that compiler warning is visible before this change and is removed after this change.
> Use @Deprecated annotation to silence compiler warnings

- src/main/java/hudson/matrix/MatrixConfiguration.java
Not declaring this unnecessary `throws` will make it easier to adapt in the future if/when the return type of the super method changes in Jenkins core to adopt EE 9.
`mvn clean verify`
> Reduce `javax.servlet.ServletException` footprint

- pom.xml
- src/main/java/hudson/matrix/LabelAxis.java
- src/main/resources/hudson/matrix/LabelAxis/config.jelly
- src/main/resources/hudson/matrix/LabelAxis/label-axis.css
- src/main/resources/hudson/matrix/LabelAxis/label-axis.js
- src/main/resources/hudson/matrix/MatrixProject/configure-entries.jelly
The LabelAxis configuration was using yahoo treeview. As yahoo is very old and deprecated we should remove this.
Generate the complete configure page in jelly and just add some small javascript to show/hide the lists with labels.
The label description is no longer printed in brackets after the label name but instead shown as a html tooltip. The MarkupFormatter is used to generate the html so it should be safe and it is displayed in the same way as on the label page.
Once merged requires changes to ATH
Before:
After:
Manually tested, that after saving all axis are properly defined
> Reimplement the UI for `LabelAxis`

- src/main/resources/lib/hudson/matrix-project/matrix.jelly
As of https://github.com/jenkinsci/jenkins/pull/4503 this always returned `false` anyway. There is no EE 9 replacement.
> Remove usage of deprecated EE 8 method

- pom.xml
- src/test/java/hudson/matrix/MatrixProjectTest.java
Adapt to https://github.com/jenkinsci/jenkins/pull/10555 as discovered by https://github.com/jenkinsci/bom/pull/4929.
> Await effects of `GlobalBuildDiscarderListener`

- src/main/resources/lib/hudson/matrix-project/matrix-styles.css
use flex-wrap to avoid that wrapping happens within a single configuration
Regression from #289
Before:
After:
> Fix wrapping for single-axis

- pom.xml
`jenkins-test-harness-tools` depends on `gradle:2.15`. This causes an issue when running PCT on megawar containing `matrix-project-plugin` and `gradle:2.16.1149.v711b_998b_0532` (see [JENKINS-76087](https://issues.jenkins.io/browse/JENKINS-76087)).
Let's exclude `gradle` which is not used from here.
I verified locally that "mvn clean test" succeeds.
> Exclude useless `gradle` test dependency
