jenkinsci/matrix-project-plugin

- src/main/java/hudson/matrix/AxisDescriptor.java
- src/test/java/hudson/matrix/AxisDescriptorTest.java
[JENKINS-28909](https://issues.jenkins-ci.org/browse/JENKINS-28909)
> [FIXED JENKINS-28909] Do not enforce 'good' chars for axis values

- pom.xml
So the trend can be viewed in Jenkins.
@reviewbybees
> Configured xml output for findbugs

- pom.xml
- src/main/java/hudson/matrix/Axis.java
- src/main/java/hudson/matrix/AxisDescriptor.java
- src/main/java/hudson/matrix/JDKAxis.java
- src/main/java/hudson/matrix/LabelAxis.java
- src/main/java/hudson/matrix/LabelExpAxis.java
- src/main/java/hudson/matrix/LinkedLogRotator.java
- src/main/java/hudson/matrix/MatrixBuild.java
- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/main/java/hudson/matrix/MatrixConfigurationSorterDescriptor.java
- src/main/java/hudson/matrix/MatrixExecutionStrategyDescriptor.java
- src/main/java/hudson/matrix/MatrixProject.java
- src/main/java/hudson/matrix/MatrixRun.java
- src/main/java/hudson/matrix/NoopMatrixConfigurationSorter.java
- src/main/java/hudson/matrix/listeners/MatrixBuildListener.java
- src/main/java/hudson/tasks/test/TestResultAggregator.java
We want to have automatic FindBugs checks in the plugin pull request builders
> Enable findbugs annotations

- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/test/java/hudson/matrix/MatrixConfigurationTest.java
[JENKINS-32423](https://issues.jenkins-ci.org/browse/JENKINS-32423)
> [FIXED JENKINS-32423] Do not show /configure for matrix configurations

- src/main/java/hudson/matrix/MatrixProject.java
This PR is motivated by [this change](https://github.com/jenkinsci/jenkins/blob/2.0/core/src/main/java/jenkins/model/item_category/StandaloneProjectsCategory.java#L35) in core
@reviewbybees especially @jglick and @daniel-beck since they proposed this change
> [JENKINS-31162] The category ID has changed

- src/main/resources/hudson/matrix/Messages_de.properties
Same as https://github.com/jenkinsci/matrix-project-plugin/pull/27 - but this time without changing umlauts
> Improve translation

- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/test/java/hudson/matrix/MatrixConfigurationTest.java
This turned out to be one of the largest contributor to allocations in production. This change
- caches the result until the configurations are updated and
- optimizes the computation itself.
@jenkinsci/code-reviewers
> Cache configuration label

- src/main/java/hudson/matrix/MatrixBuild.java
- src/main/java/hudson/matrix/MatrixProject.java
- src/test/java/hudson/matrix/MatrixTest.java
- src/test/java/hudson/matrix/helper/DynamicTestAxis.java
Fixed handling of concurrent builds with different axis by adding a mutex and deep copy the AxisList.
https://issues.jenkins-ci.org/browse/JENKINS-34389
> [JENKINS-34389] Fixed handling of dynamic axis

- src/main/java/hudson/matrix/MatrixChildParametersAction.java
- src/main/java/hudson/matrix/MatrixRun.java
> Polishing #45

- pom.xml
- src/test/java/hudson/matrix/AxisTest.java
- src/test/java/hudson/matrix/LabelExpAxisTest.java
- src/test/java/hudson/matrix/MatrixChildParametersActionTest.java
- src/test/java/hudson/matrix/MatrixConfigurationSorterTest.java
- src/test/java/hudson/matrix/MatrixConfigurationTest.java
- src/test/java/hudson/matrix/MatrixProjectCustomWorkspaceTest.java
- src/test/java/hudson/matrix/MatrixProjectDependencyTest.java
- src/test/java/hudson/matrix/MatrixProjectTest.java
- src/test/java/hudson/matrix/MatrixTest.java
- src/test/java/hudson/matrix/RestartingRestoreTest.java
[JENKINS-43990](https://issues.jenkins-ci.org/browse/JENKINS-43990)
- Update to 2.X parent POM.
- Bump Jenkins and plugins versions.
- Fix tests errors.
@reviewbybees @jglick @kwhetstone @andresrc @olivergondza
> [JENKINS-43990] Update to 2.X parent POM

- pom.xml
According to wiki, Oliver Gondza is the maintainer of the plugin. It would be interesting to keep that information in the POM file.
@reviewbybees
> Maintainer information in pom.xml

- src/main/java/hudson/matrix/Axis.java
- src/main/java/hudson/matrix/AxisList.java
- src/main/java/hudson/matrix/Layouter.java
- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/main/java/hudson/matrix/MatrixProject.java
- src/main/java/hudson/matrix/listeners/MatrixBuildListener.java
- src/main/java/hudson/tasks/test/MatrixTestResult.java
- src/test/java/hudson/matrix/CombinationFilterUsingBuildParamsTest.java
- src/test/java/hudson/matrix/CombinationTest.java
- src/test/java/hudson/matrix/MatrixChildParametersActionTest.java
- src/test/java/hudson/matrix/MatrixConfigurationTest.java
- src/test/java/hudson/matrix/MatrixProjectTest.java
Resolved most of the warnings. Some still exist.
> Fix warnings

- pom.xml
- src/test/java/hudson/matrix/MatrixProjectTest.java
I can release this if I can get [INFRA-2642](https://issues.jenkins-ci.org/browse/INFRA-2642) (@timja et al.).
> Updated parent, deps, BOM

- src/main/java/hudson/tasks/test/MatrixTestResult.java
Regression in #56 by @orgads found by https://github.com/jenkinsci/bom/pull/251.
> Fixing ClassCastException found by PCT

- pom.xml
Chose 2.249 to match https://github.com/jenkinsci/matrix-project-plugin/pull/63
cc @jglick
> Bump core dependency - drop implied deps

- README.md
- src/main/java/hudson/matrix/FilterScript.java
- src/main/java/hudson/matrix/MatrixConfiguration.java
- src/main/resources/hudson/matrix/MatrixProject/help-slaveAffinity.html
- src/main/resources/hudson/matrix/Messages_da.properties
- src/main/webapp/help/matrix/combinationfilter.html
- src/test/java/hudson/matrix/MatrixProjectTest.java
Terminology update as part of [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398).
> [JENKINS-65398] Terminology update

- src/test/java/hudson/matrix/RestartingRestoreTest.java
We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`
> Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

- src/main/java/hudson/matrix/Axis.java
- src/main/java/hudson/matrix/LabelAxis.java
- src/main/java/hudson/matrix/MatrixProject.java
Adapts to jenkinsci/jenkins#5467.
> Stop using deprecated `Util#join`

- pom.xml
[JENKINS-55582](https://issues.jenkins-ci.org/browse/JENKINS-55582) Convert modules to plugins
[JENKINS-64107](https://issues.jenkins-ci.org/browse/JENKINS-64107) Convert SSHD module to a plugin
[JEP](https://github.com/jenkinsci/jep/pull/326) Convert modules to plugins
* This PR change to use the  sshd-plugin
* Bump the Core to the 2.282
> [JENKINS-64107] Convert SSHD module to a plugin

- pom.xml
- src/main/java/hudson/matrix/LabelAxis.java
- src/main/resources/hudson/matrix/LabelAxis/config.jelly
⚠️ This PR should be merged using merge-commit, not using squash-commit or rebase-commit, to ensure the commits related to the release are on the history of the default branch.
> Integrate security fix from 1.20

- src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
- src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
The change proposed utilizes the new build status, like it's used it other parts of Jenkins.
turns into
> [JENKINS-66450] Utilize new build status

- pom.xml
- src/main/resources/hudson/matrix/MatrixProject/configure-entries.jelly
As part of https://github.com/jenkinsci/jenkins/pull/6485 the new job config screen will have a toggle for a project's state in the top right by default, so there's no need to duplicate this.
---
> Remove disable checkbox

- src/main/resources/hudson/matrix/LabelAxis/config.jelly
Tested by running PCT both with and without this PR against a core without Prototype. Before this PR, failed. After this PR, passed.
> Remove usages of Prototype

- README.md
> Fix link text in README.md

- pom.xml
- src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
- src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/399
Created a few matrix projects.
Tested nobuild, aborted, success.
Icons all look good (better than before as there was some rendering issues previously with text too close to icons)
```[tasklist]
```
> Adapt to new build symbols (requires 2.434)

- src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
- src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
- src/main/resources/lib/hudson/matrix-project/matrix.jelly
Regression from https://github.com/jenkinsci/matrix-project-plugin/pull/183
See https://issues.jenkins.io/browse/JENKINS-73225
A couple of other minor tweaks:
- tooltips on the text rather than the cell (previously some were widely off appearing in the right place)
- switched to `jenkins-table` and used headers for the table, it doesn't look fully right as its a nested table which is illegal and requires https://github.com/jenkinsci/jenkins/pull/5351 to be picked up again to be fully functional
I added the example from the README: https://github.com/jenkinsci/matrix-project-plugin#configuration-matrix
and tested it:
> [JENKINS-73225] - Restore linking when multiple axes

- src/main/resources/hudson/matrix/MatrixBuild/ajaxMatrix.jelly
- src/main/resources/hudson/matrix/MatrixProject/ajaxMatrix.jelly
- src/main/resources/lib/hudson/matrix-project/matrix.jelly
https://issues.jenkins.io/browse/JENKINS-73225?focusedId=447376&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-447376
- Restored opacity for not run configurations, `l:icon` with symbols doesn't support the style attribute, it needs wrapping in something else
- Tooltips now disappear on table refresh, see https://github.com/jenkinsci/jenkins/pull/9263, tooltip needed to be moved to a higher element as `l:icon` doesn't support the tooltip placement attribute
- Removed not run and not configured text that looks to have been accidentally added which was breaking the layout for larger configurations
Used the example matrix from the issue and it looked awful but readable.
I wouldn't recommend using the example one yourself and if you do delete it after, it …
> Layout fixes

- src/main/java/hudson/matrix/MatrixProject.java
Untested, but a similar change was made in https://github.com/jenkinsci/workflow-job-plugin/pull/411 without any issues.
> Clean up after jenkinsci/jenkins#9150

- src/main/java/hudson/matrix/MatrixBuild.java
- src/test/java/hudson/matrix/MatrixTest.java
> remove usage of commons-lang

- pom.xml
- src/main/resources/hudson/matrix/DefaultMatrixExecutionStrategyImpl/config.groovy
- src/main/resources/lib/hudson/matrix-project/matrix-styles.css
- src/main/resources/lib/hudson/matrix-project/matrix.jelly
Use jenkins-table to display the matrix-combination table 
don't use styles defined in core
Update to 2.492.3
Before on 2.479.3:
Before on 2.516.1:
After on 2.492.3:
After on 2.516.1:
Also contains some minor adjustments so the matrix-combinations-parameter plugin can reuse the matrix.jelly instead of maintaining an almost identical copy.
Tested that the table is readable with all themes: default, dark, solarized (dark and light), chocolate on 2.516.1
> [JENKINS-75924] fix matrix table with dark-theme
